### ISSUE TITLE
1.9.5 版本默认会直接在菜单中列出所有语言

### ISSUE THREAD

**Issue by LenKiMo** [rexdf/ChineseLocalization#11]
Windows 10 Pro 64-Bit
在 Sublime Text 3 Build 3114/3122 64-Bit Portable 下均呈现如下图示状态：
https://ooo.0o0.ooo/2016/09/16/57db7ba713ad9.png

所有菜单下都是如此，点击重置亦无帮助。

**Comment by CrazyPlace** [comment]
我这里遇到了同样的问题
Windows 10 Edu 64bit
Sublime Text 3 Build 3114
图片类似，就不截图了

**Comment by LeoSpark** [comment]
我也遇到同样问题，
Windows 10 Sublime Text 3 Build 3114
现在只好删除部分安装包文件，作为临时解决办法

**Comment by rexdf** [comment]
已更新，问题在于为了支持新版，忘记加后缀了。

**Comment by rexdf** [comment]
下次我还是先本地测试下，因为程序逻辑上几乎没动，所以没测试就做了个release。

**Comment by LenKiMo** [comment]
已经在 Package Control 中确认到了新版本更新，问题解决。
