### ISSUE TITLE
我手动安装后需要怎么配置么，现在是所有语言都显示啊

### ISSUE THREAD

**Issue by zhizunbao84** [rexdf/ChineseLocalization#12]
我是win8系统，64位，sublimetext3的3126版本，手动下载解压后放到Sublime Text Build 3126 x64\Data\Packages下面，打开sublime text后所有语言都显示，不论我选择什么语言。

**Comment by rexdf** [comment]
手动下载的话 选择 release分支 这个页面下载 https://github.com/rexdf/ChineseLocalization/releases 
用zip压缩包。

实际上就是切换到st3分支下载。
