### ISSUE TITLE
使用ChineseLocalizations后无法更改语言

### ISSUE THREAD

**Issue by StubbornYang** [rexdf/ChineseLocalization#13]
Download Zip 后更改文件名及后缀放入 packages 文件夹 无法更改语言
st3-dev 默认日本语无法更改语言
st3 默认英语无法更改语言
MAC 10.12.4    Sublime Text 3 Build 3126
![image](https://cloud.githubusercontent.com/assets/23377286/25397257/4573485e-2a1a-11e7-9793-e5694511b071.png)

**Comment by rexdf** [comment]
st3-dev是不能用的，因为翻译都是展开的。

st3应该是可以的。

推荐使用PackageControl管理插件。首先选择Tools下面的Install Package Control。然后搜素chinese可以找到本插件。

**Comment by rexdf** [comment]
嗯 确实不行。原因在于下载的zip包，打开看，发现里面存在`ChineseLocalization-st3``这样的子目录，这就是问题关键了。如果没有这个目录，直接是文件才行。
