### ISSUE TITLE
首选项菜单中翻译-/–能否替换一致？

### ISSUE THREAD

**Issue by h1orz** [rexdf/ChineseLocalization#14]
首选项 -> 设置 – 特定语法
首选项 -> 设置 - 无干扰模式

两项翻译中 -/– 符号不一致，能否弄成一致？繁体中文时，这里也不一致。
强迫症看着受不了，每次都自己手动改，这次升级又要改一下，哈哈[喜极而泣]

**Comment by rexdf** [comment]
应该是修复了

**Comment by h1orz** [comment]
幸苦辛苦~
