### ISSUE TITLE
最新版本的ChineseL10n在Sublime3Build3126上的问题

### ISSUE THREAD

**Issue by Hydroge** [rexdf/ChineseLocalization#15]
![problem](https://cloud.githubusercontent.com/assets/26434230/26274060/07f02c52-3d72-11e7-9937-7b91904d5145.png)
# ***这里，“主题”和“配色方案”选项都是灰色的！！！***

**Comment by rexdf** [comment]
推荐使用 3131，方法谷歌。3131的翻译是更新过的，应该完全等效英文。

粗略看了下，这个问题似乎由来已久，不仅仅是3126，似乎3100都有这个问题，暂时还没定位到哪一版本开始的改动。晚些时候我再更新。
