### ISSUE TITLE
想问问怎么解决这个tools中文显示

### ISSUE THREAD

**Issue by xxxycl** [rexdf/ChineseLocalization#16]
如下图所示，我只是想问问这个tools中文应该怎么解决。

如果有空，就麻烦您告诉我了，谢谢。

![image](https://user-images.githubusercontent.com/10785793/27983833-c652d418-63f8-11e7-9c87-32e9085ee460.png)

**Comment by rexdf** [comment]
你这不是我的版本，不知道你如何装成了windows版本的。 推荐使用Sublime Text 3 最新的开发版或者稳定版。 推荐安装之后立即从菜单安装PackageControl，推荐使用PackageControl安装ChineseLocalization。

请提供 sublime版本，ChineseLocalization版本(如果是PackageControl安装，则不需要操心，会自动更新)。 

最近3132之后的版本我没有追踪，等有时间一起更新。

**Comment by rexdf** [comment]
我猜你是从Windows直接复制文件过来的，那么切换一下语言吧。先切换到日语或者繁体中文，再切换回简体中文应该就好了。
