### ISSUE TITLE
(Question) Use your files...

### ISSUE THREAD

**Issue by vanja-san** [rexdf/ChineseLocalization#22]
Can I use your files to create my own language for Sublime Text? **_All copyrights will be listed!_**
And by the way ... On the portable version of ST3, the language is not deleted, that is, it does not return by default, so it remains.

**Comment by rexdf** [comment]
Yes, you can use those files. They are under MIT License.

Actually, I only test it with portable version.

Are you meaning deleted or detecting?

If detecting, try `from locale import getdefaultlocale;getdefaultlocale()` in console.

If deleted. Are you meaning when you uninstall this plugin by packagecrontol, it not recovery to English ?

This plugin is designed to work with packagecrontol.
