### ISSUE TITLE
I updated Russian translate!

### ISSUE THREAD

**Issue by vanja-san** [rexdf/ChineseLocalization#46]
- Minimal changes
- I tried to add a translation of the line "Language".
- Maybe it wasn't necessary to remove commas, but I took a chance! Correct if i wrong. 😏

`Please see my fork:`
https://github.com/vanja-san/ChineseLocalization

**Comment by rexdf** [comment]
json does not support trailing comma and comments. 

sublime supports both.

**Comment by rexdf** [comment]
But comma doesn't matter.

It looks good to me. You can make a pull request if you like.

**Comment by rexdf** [comment]
It seems that the repo has been deleted.

**Comment by vanja-san** [comment]
OMG! I stupid. Sorry! 😓 i fix it
