### ISSUE TITLE
关于"Show Unsaved Changes…"的汉化

### ISSUE THREAD

**Issue by maboloshi** [rexdf/ChineseLocalization#50]
这个菜单项由 ST 自带插件`Diff.sublime-package`引入
由于该插件`Context.sublime-menu`菜单中未使用`id`, 所以无法合并到`Default\Context.sublime-menu`

只能在package下创建`Diff`文件夹 放入汉化的`Context.sublime-menu`

```json
[
	{ "caption": "-", "id": "diff" },
	{ "caption": "显示未保存的更改…", "command": "diff_changes" }
]

```
<img width="384" alt="截屏2020-07-05下午1 53 07" src="https://user-images.githubusercontent.com/7850715/86526461-ef8cb700-bec6-11ea-9164-dda5aef22291.png">

**Comment by rexdf** [comment]
当初想过“宏大”的一个计划，就是对其他package也做类似Default的事情，甚至还考虑过设计一个类似packagecontrol.io的外部贡献提交repo来接收外部的翻译文件，后来咕咕咕掉了

当时还占位了一个组织 😳

https://github.com/SublimeText-i18n

**Comment by maboloshi** [comment]
https://github.com/maboloshi/sublime-text-chinese/tree/dev/DiffTabs
