### ISSUE TITLE
ignored_packages配置项总是被覆盖回去

### ISSUE THREAD

**Issue by bokix** [rexdf/ChineseLocalization#56]
这项目已经不维护了吗？

我一个插件一个插件的测试，发现只要装了ChineseLocalization， sublme的用户配置中的这个配置项：
`"ignored_packages":["Vintage" ]`
在启动的时候就会被覆盖成：
`"ignored_packages":[ ]`

以下是日志：
```
reloading plugin HTML.html_completions
reloading python 3.3 plugin MarkdownPreview.markdown_settings
reloading python 3.3 plugin MarkdownPreview.markdown_wrapper
reloading python 3.3 plugin OpenHere.openhere
reloading plugin Package Control.plugin
reloading python 3.3 plugin Codecs33.Codecs33
reloading plugin ConvertToUTF8.ConvertToUTF8
plugins loaded
ignored packages updated to: []
reloading settings Packages/User/Package Control.sublime-settings
reloading plugin Vintage.vintage
reloading plugin Vintage.vintage_commands
reloading plugin Vintage.vintage_motions
reloading settings Packages/User/Preferences.sublime-settings
```

只要删了此插件，就不会再发生上述问题。

sublime版本：sublime 4169

**Comment by neo515** [comment]
same to you. 
i removed the package to resolve the promble.
https://github.com/rexdf/ChineseLocalization/issues/57

**Comment by neo515** [comment]
> same to you. i removed the package to resolve the promble. #57

据说手动安装一次"Vintage"包, 可以规避这个问题.

**Comment by bokix** [comment]
我改用另一个插件了，这项目的主页上就有链接，估计是这个作者另起炉灶了。[zam1024t](https://github.com/zam1024t)
/
[LocalizedMenu](https://github.com/zam1024t/LocalizedMenu)

**Comment by PHarr-mx** [comment]
我也是尝试改了很多次，我甚至在系统设置文件为只读格式依旧不行，最后卸载了这个插件解决了
