### ISSUE TITLE
更新新版本后，首选项配置不可点击

### ISSUE THREAD

**Issue by liuhuapiaoyuan** [rexdf/ChineseLocalization#9]
![image](https://cloud.githubusercontent.com/assets/8020726/16756506/32b59fd8-4838-11e6-9df6-aa91d6ba7ac1.png)

**Comment by rexdf** [comment]
打开Sublime之后要等一会，后台插件加载完成就可点击了。另外这里的几个菜单要求3099(大约)以上的版本才有效。我测试的3118是可以点击的，3114应该也是可以的。

目前更新的翻译按照最新的英文来的，所以对老版本有部分不兼容。 具体来说就是 这里的设置选项，还有就是工具下面的取消编译菜单，以及插件开发菜单。

如果在使用3099以前的版本，一个临时的解决办法是换到英文去改设置，因为现在英文会保证使用Sublime Text自带的内置英文版，保证一定匹配，这个对老版本是一个兼容。

**Comment by rexdf** [comment]
好吧 我错了！ 这个修改是3118开始的！！ 我对3114做下兼容。

**Comment by rexdf** [comment]
1.9.1已解决
